CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260831112859_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260831112859_InitialCreate', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" uuid NOT NULL,
        "DisplayName" character varying(100) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE TABLE "RefreshTokens" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "TokenHash" character varying(128) NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedByIp" character varying(64),
        "RevokedAt" timestamp with time zone,
        "ReplacedByTokenId" uuid,
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE UNIQUE INDEX "IX_RefreshTokens_TokenHash" ON "RefreshTokens" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    CREATE INDEX "IX_RefreshTokens_UserId_RevokedAt_ExpiresAt" ON "RefreshTokens" ("UserId", "RevokedAt", "ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901095449_IdentityAndRefreshTokens') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260901095449_IdentityAndRefreshTokens', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901140137_FinancialAccountsAndTransactions') THEN
    CREATE TABLE account_connections (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "InstitutionId" uuid NOT NULL,
        "ExternalConnectionId" character varying(150) NOT NULL,
        "Status" character varying(50) NOT NULL,
        "LastSuccessfulSyncAt" timestamp with time zone,
        "LastSyncAttemptAt" timestamp with time zone,
        "LastSyncError" character varying(1000),
        "SyncCursor" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_account_connections" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901140137_FinancialAccountsAndTransactions') THEN
    CREATE TABLE financial_accounts (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "ConnectionId" uuid NOT NULL,
        "InstitutionId" uuid NOT NULL,
        "ExternalAccountId" character varying(150) NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Type" character varying(50) NOT NULL,
        "Currency" character varying(3) NOT NULL,
        "CurrentBalance" numeric(18,2) NOT NULL,
        "AvailableBalance" numeric(18,2) NOT NULL,
        "Status" character varying(50) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_financial_accounts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901140137_FinancialAccountsAndTransactions') THEN
    CREATE TABLE institutions (
        "Id" uuid NOT NULL,
        "ProviderCode" character varying(50) NOT NULL,
        "Name" character varying(150) NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_institutions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901140137_FinancialAccountsAndTransactions') THEN
    CREATE TABLE transactions (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "AccountId" uuid NOT NULL,
        "InstitutionId" uuid NOT NULL,
        "ProviderTransactionId" character varying(200) NOT NULL,
        "RawDescription" character varying(1000) NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Currency" character varying(3) NOT NULL,
        "TransactionDate" timestamp with time zone NOT NULL,
        "Type" character varying(50) NOT NULL,
        "Status" character varying(50) NOT NULL,
        "Fingerprint" character varying(128) NOT NULL,
        "ImportedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_transactions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901140137_FinancialAccountsAndTransactions') THEN
    CREATE UNIQUE INDEX "IX_account_connections_ExternalConnectionId" ON account_connections ("ExternalConnectionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901140137_FinancialAccountsAndTransactions') THEN
    CREATE INDEX "IX_account_connections_UserId_InstitutionId" ON account_connections ("UserId", "InstitutionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901140137_FinancialAccountsAndTransactions') THEN
    CREATE UNIQUE INDEX "IX_financial_accounts_ConnectionId_ExternalAccountId" ON financial_accounts ("ConnectionId", "ExternalAccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901140137_FinancialAccountsAndTransactions') THEN
    CREATE UNIQUE INDEX "IX_institutions_ProviderCode" ON institutions ("ProviderCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901140137_FinancialAccountsAndTransactions') THEN
    CREATE UNIQUE INDEX "IX_transactions_AccountId_ProviderTransactionId" ON transactions ("AccountId", "ProviderTransactionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901140137_FinancialAccountsAndTransactions') THEN
    CREATE INDEX "IX_transactions_Fingerprint" ON transactions ("Fingerprint");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901140137_FinancialAccountsAndTransactions') THEN
    CREATE INDEX "IX_transactions_UserId_TransactionDate" ON transactions ("UserId", "TransactionDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260901140137_FinancialAccountsAndTransactions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260901140137_FinancialAccountsAndTransactions', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    ALTER TABLE transactions ADD "CategoryId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    ALTER TABLE transactions ADD "ClassificationConfidence" numeric(5,4);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    ALTER TABLE transactions ADD "ClassificationSource" character varying(50) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    ALTER TABLE transactions ADD "ClassificationStatus" character varying(50) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    ALTER TABLE transactions ADD "ClassifiedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    ALTER TABLE transactions ADD "MerchantId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    ALTER TABLE transactions ADD "NormalizedDescription" character varying(1000) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    ALTER TABLE transactions ADD "SubcategoryId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    ALTER TABLE transactions ADD "UserCorrectedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    CREATE TABLE categories (
        "Id" uuid NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Type" character varying(50) NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_categories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    CREATE TABLE merchant_aliases (
        "Id" uuid NOT NULL,
        "MerchantId" uuid NOT NULL,
        "Alias" character varying(300) NOT NULL,
        CONSTRAINT "PK_merchant_aliases" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    CREATE TABLE merchants (
        "Id" uuid NOT NULL,
        "CanonicalName" character varying(200) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_merchants" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    CREATE TABLE subcategories (
        "Id" uuid NOT NULL,
        "CategoryId" uuid NOT NULL,
        "Code" character varying(50) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_subcategories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    CREATE INDEX "IX_transactions_CategoryId" ON transactions ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    CREATE INDEX "IX_transactions_MerchantId" ON transactions ("MerchantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    CREATE UNIQUE INDEX "IX_categories_Code" ON categories ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    CREATE UNIQUE INDEX "IX_merchant_aliases_Alias" ON merchant_aliases ("Alias");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    CREATE INDEX "IX_merchant_aliases_MerchantId" ON merchant_aliases ("MerchantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    CREATE UNIQUE INDEX "IX_merchants_CanonicalName" ON merchants ("CanonicalName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    CREATE INDEX "IX_subcategories_CategoryId" ON subcategories ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    CREATE UNIQUE INDEX "IX_subcategories_Code" ON subcategories ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902122606_TransactionIntelligence') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260902122606_TransactionIntelligence', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903102618_SubscriptionIntelligence') THEN
    CREATE TABLE subscription_price_history (
        "Id" uuid NOT NULL,
        "SubscriptionId" uuid NOT NULL,
        "TransactionId" uuid NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "ObservedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_subscription_price_history" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903102618_SubscriptionIntelligence') THEN
    CREATE TABLE subscriptions (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "MerchantId" uuid NOT NULL,
        "MerchantName" character varying(200) NOT NULL,
        "Currency" character varying(3) NOT NULL,
        "Frequency" character varying(50) NOT NULL,
        "CurrentAmount" numeric(18,2) NOT NULL,
        "AverageAmount" numeric(18,2) NOT NULL,
        "DetectionConfidence" numeric(5,4) NOT NULL,
        "FirstDetectedAt" timestamp with time zone NOT NULL,
        "LastChargeAt" timestamp with time zone NOT NULL,
        "NextExpectedChargeAt" timestamp with time zone,
        "LastPriceChangedAt" timestamp with time zone,
        "Status" character varying(50) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_subscriptions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903102618_SubscriptionIntelligence') THEN
    CREATE INDEX "IX_subscription_price_history_SubscriptionId_ObservedAt" ON subscription_price_history ("SubscriptionId", "ObservedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903102618_SubscriptionIntelligence') THEN
    CREATE UNIQUE INDEX "IX_subscription_price_history_SubscriptionId_TransactionId" ON subscription_price_history ("SubscriptionId", "TransactionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903102618_SubscriptionIntelligence') THEN
    CREATE INDEX "IX_subscriptions_NextExpectedChargeAt" ON subscriptions ("NextExpectedChargeAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903102618_SubscriptionIntelligence') THEN
    CREATE UNIQUE INDEX "IX_subscriptions_UserId_MerchantId_Currency" ON subscriptions ("UserId", "MerchantId", "Currency");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903102618_SubscriptionIntelligence') THEN
    CREATE INDEX "IX_subscriptions_UserId_Status" ON subscriptions ("UserId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260903102618_SubscriptionIntelligence') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260903102618_SubscriptionIntelligence', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260904095953_AnomalyDetectionAndFinancialInsights') THEN
    CREATE TABLE anomalies (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "TransactionId" uuid NOT NULL,
        "AccountId" uuid NOT NULL,
        "Type" character varying(60) NOT NULL,
        "Severity" character varying(30) NOT NULL,
        "Score" numeric(5,4) NOT NULL,
        "Confidence" numeric(5,4) NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Description" character varying(1000) NOT NULL,
        "Evidence" character varying(2000) NOT NULL,
        "DetectedAt" timestamp with time zone NOT NULL,
        "Status" character varying(30) NOT NULL,
        "ResolvedAt" timestamp with time zone,
        CONSTRAINT "PK_anomalies" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260904095953_AnomalyDetectionAndFinancialInsights') THEN
    CREATE TABLE financial_insights (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "AnomalyId" uuid,
        "TransactionId" uuid,
        "Type" character varying(60) NOT NULL,
        "Severity" character varying(30) NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Message" character varying(1500) NOT NULL,
        "OccurredAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone,
        "Status" character varying(30) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_financial_insights" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260904095953_AnomalyDetectionAndFinancialInsights') THEN
    CREATE UNIQUE INDEX "IX_anomalies_TransactionId_Type" ON anomalies ("TransactionId", "Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260904095953_AnomalyDetectionAndFinancialInsights') THEN
    CREATE INDEX "IX_anomalies_UserId_Severity_DetectedAt" ON anomalies ("UserId", "Severity", "DetectedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260904095953_AnomalyDetectionAndFinancialInsights') THEN
    CREATE INDEX "IX_anomalies_UserId_Status_DetectedAt" ON anomalies ("UserId", "Status", "DetectedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260904095953_AnomalyDetectionAndFinancialInsights') THEN
    CREATE INDEX "IX_financial_insights_AnomalyId" ON financial_insights ("AnomalyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260904095953_AnomalyDetectionAndFinancialInsights') THEN
    CREATE INDEX "IX_financial_insights_UserId_Status_CreatedAt" ON financial_insights ("UserId", "Status", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260904095953_AnomalyDetectionAndFinancialInsights') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260904095953_AnomalyDetectionAndFinancialInsights', '10.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260905165039_ProductionHardeningNotificationsOutboxAudit') THEN
    CREATE TABLE audit_events (
        "Id" uuid NOT NULL,
        "UserId" uuid,
        "EventType" character varying(100) NOT NULL,
        "IpAddress" character varying(64),
        "CorrelationId" character varying(100),
        "TraceId" character varying(100),
        "Metadata" jsonb,
        "OccurredAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_audit_events" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260905165039_ProductionHardeningNotificationsOutboxAudit') THEN
    CREATE TABLE notification_preferences (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "InAppEnabled" boolean NOT NULL,
        "EmailEnabled" boolean NOT NULL,
        "AnomalyNotificationsEnabled" boolean NOT NULL,
        "SubscriptionNotificationsEnabled" boolean NOT NULL,
        "InsightNotificationsEnabled" boolean NOT NULL,
        CONSTRAINT "PK_notification_preferences" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260905165039_ProductionHardeningNotificationsOutboxAudit') THEN
    CREATE TABLE notifications (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Type" character varying(60) NOT NULL,
        "Channel" character varying(30) NOT NULL,
        "Title" character varying(250) NOT NULL,
        "Message" character varying(5000) NOT NULL,
        "DeduplicationKey" character varying(300),
        "Status" character varying(30) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "DeliveredAt" timestamp with time zone,
        "ReadAt" timestamp with time zone,
        "AttemptCount" integer NOT NULL,
        "LastError" character varying(2000),
        CONSTRAINT "PK_notifications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260905165039_ProductionHardeningNotificationsOutboxAudit') THEN
    CREATE TABLE outbox_messages (
        "Id" uuid NOT NULL,
        "EventType" character varying(500) NOT NULL,
        "Payload" jsonb NOT NULL,
        "RoutingKey" character varying(250) NOT NULL,
        "OccurredAt" timestamp with time zone NOT NULL,
        "LastAttemptedAt" timestamp with time zone,
        "AttemptCount" integer NOT NULL,
        "Status" character varying(30) NOT NULL,
        "LastError" character varying(2000),
        "PublishedAt" timestamp with time zone,
        "NextAttemptAt" timestamp with time zone,
        CONSTRAINT "PK_outbox_messages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260905165039_ProductionHardeningNotificationsOutboxAudit') THEN
    CREATE TABLE processed_messages (
        "Id" uuid NOT NULL,
        "MessageId" character varying(200) NOT NULL,
        "ConsumerName" character varying(200) NOT NULL,
        "ProcessedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_processed_messages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260905165039_ProductionHardeningNotificationsOutboxAudit') THEN
    CREATE INDEX "IX_audit_events_EventType_OccurredAt" ON audit_events ("EventType", "OccurredAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260905165039_ProductionHardeningNotificationsOutboxAudit') THEN
    CREATE INDEX "IX_audit_events_UserId_OccurredAt" ON audit_events ("UserId", "OccurredAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260905165039_ProductionHardeningNotificationsOutboxAudit') THEN
    CREATE UNIQUE INDEX "IX_notification_preferences_UserId" ON notification_preferences ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260905165039_ProductionHardeningNotificationsOutboxAudit') THEN
    CREATE INDEX "IX_notifications_UserId_DeduplicationKey" ON notifications ("UserId", "DeduplicationKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260905165039_ProductionHardeningNotificationsOutboxAudit') THEN
    CREATE INDEX "IX_notifications_UserId_Status_CreatedAt" ON notifications ("UserId", "Status", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260905165039_ProductionHardeningNotificationsOutboxAudit') THEN
    CREATE INDEX "IX_outbox_messages_Status_NextAttemptAt_OccurredAt" ON outbox_messages ("Status", "NextAttemptAt", "OccurredAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260905165039_ProductionHardeningNotificationsOutboxAudit') THEN
    CREATE UNIQUE INDEX "IX_processed_messages_MessageId_ConsumerName" ON processed_messages ("MessageId", "ConsumerName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260905165039_ProductionHardeningNotificationsOutboxAudit') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260905165039_ProductionHardeningNotificationsOutboxAudit', '10.0.11');
    END IF;
END $EF$;
COMMIT;

